### ISSUE TITLE
What is the meaning of 0,1,2 in mask?

### ISSUE THREAD

**Issue by AboveParadise** [ZhouCX117/UAED#11]
In function cross_entropy_loss_RCF, what is the meaning of 0,1,2 in mask?

**Comment by ZhouCX117** [comment]
In UAED, 0 means non-edge pixels, 1 means edge pixels, and 2 equals zero. For previous methods, 2 means noisy labels whose average values are lower than 0.3 and higher than 0.

**Comment by AboveParadise** [comment]
Thanks, that helps a lot!
