### ISSUE TITLE
Questions about the provided dataset

### ISSUE THREAD

**Issue by Star-xing1** [ZhouCX117/UAED#13]
The provided dataset (from the Baidu network disk you provided) does not correspond to the files in /data_file/train_val_all.lst, that is, some files (groundTruth) in /data_file/train_val_all.lst do not exist in the provided dataset.
Like this:
![f8dfda8e950ce1880d41a3628db9c6d](https://github.com/ZhouCX117/UAED/assets/83267809/44030b22-e1af-4b37-bf58-428aebc88829)
If /data_file/train_val_all.lst should not be used for training, which one should I use instead?

**Comment by ZhouCX117** [comment]
Please download the complete dataset from the provided Google disk, or you can deal with the Val dataset using the provided code downloaded from the Baidu Disk.

**Comment by Star-xing1** [comment]
Thans a lot!
