### ISSUE TITLE
Could you please provide the code for evaluation?

### ISSUE THREAD

**Issue by Star-xing1** [ZhouCX117/UAED#14]
I used the evaluation code of pidinet (ICCV 2021) to evaluate the checkpoint you provided. The evaluation results are the same as those reported in the paper in terms of ODS and OIS indicators, but there is a large difference in the AP indicator (the difference is 0.03).
So I'd like to request a copy of the code you use to evaluate your results in your work.

**Comment by ZhouCX117** [comment]
You can refer "https://github.com/MengyangPu/EDTER/tree/main/eval".

**Comment by Star-xing1** [comment]
THANKS!

**Comment by Star-xing1** [comment]
The evaluation results are still the same as before, with significant differences in AP indicators. I used the code you provided for the inference of the model. May I ask where the problem may be?

> You can refer "https://github.com/MengyangPu/EDTER/tree/main/eval".

**Comment by ZhouCX117** [comment]
I use the same eval code as EDTER. Maybe you can have a careful check, or you can send me the results (cxzhou@bjtu.edu.cn).

**Comment by Star-xing1** [comment]
Thank you a lot!
