### ISSUE TITLE
你好，为什么我在训练的时候损失函数出现先减后增加的情况呢

### ISSUE THREAD

**Issue by yx-yyds** [ZhouCX117/UAED#15]
![20231129092150](https://github.com/ZhouCX117/UAED/assets/129817552/7ffce822-ae5c-4e2b-9062-ef35143cb0b3)

**Comment by ZhouCX117** [comment]
有时候会存在一些过拟合的现象，在中间epoch达到最好的结果。

**Comment by yx-yyds** [comment]
您在训练的时候也遇到过这种情况吗

**Comment by ZhouCX117** [comment]
有遇见过

**Comment by yx-yyds** [comment]
好的，谢谢
