### ISSUE TITLE
数据集相关

### ISSUE THREAD

**Issue by liusandao431** [ZhouCX117/UAED#16]
你好，可以共享一下您的训练数据集吗？train_root="/data/private/zhoucaixia/workspace/UD_Edge/"

**Comment by ZhouCX117** [comment]
BSDS的放在网盘了，你可以在readme里面看下。

**Comment by liusandao431** [comment]
非常感谢您。主要是想问一下您验证集对应的图像和多类标签。在网盘中的BSDS数据集中的验证集好像并没有扩展。

**Comment by liusandao431** [comment]
好嘞，非常感谢
