### ISSUE TITLE
您好，请问如何使用您提供的权重文件实现对自建数据集的边缘检测任务？

### ISSUE THREAD

**Issue by KinberAlan** [ZhouCX117/UAED#19]

**Comment by ZhouCX117** [comment]
我上传了一个测试文件，你把你的数据集路径写进test.lst文档，然后把相应的路径名换掉就可以了。数据尺寸如果是除以8除不尽的数，就按照现在的这种少个像素点的方式；如果可以除尽8，就可以把那个删掉。如果太大了，可以用side inference的方式，我放在test_sigma_logit_multicue里面了。

**Comment by KinberAlan** [comment]
> 我上传了一个测试文件，你把你的数据集路径写进test.lst文档，然后把相应的路径名换掉就可以了。数据尺寸如果是除以8除不尽的数，就按照现在的这种少个像素点的方式；如果可以除尽8，就可以把那个删掉。如果太大了，可以用side inference的方式，我放在test_sigma_logit_multicue里面了。

好的，非常感谢！

**Comment by wenya1994** [comment]
您好，8是怎么来的呀，我的数据集每个图像的大小都不一样，把所有图像都以补0的方式扩大到最小能被8整除的，但是还是会报错，调成可以被32整除的时候，大部分可以处理，还有些尺寸处理不了的

**Comment by ZhouCX117** [comment]
不好意思哈，是我表述失误，是32倍，因为Encode在编码的过程中最高下采样了32倍，如果不是32的倍数会出现奇数，然后报错。改成32倍不能处理的是哪些尺寸呢？

**Comment by wenya1994** [comment]
抱歉，是其他问题，这个问题已经解决了，32倍可以处理所有的图片了，非常感谢您的及时回复
