### ISSUE TITLE
multicue数据集

### ISSUE THREAD

**Issue by yx-yyds** [ZhouCX117/UAED#20]
你好，你可以提供你训练使用的multicue数据集吗

**Comment by ZhouCX117** [comment]
我在readme更新啦，你可以看看。链接是https://pan.quark.cn/s/d87cad9abe2e，lst文本中路径我写的是绝对路径，所以需要你自己修改下啦。

**Comment by qinhongshuai** [comment]
你好，可以提供一下：data.data_loader_one_random_multicue_uncert这个文件吗

**Comment by wenya1994** [comment]
老师您好，data.data_loader_one_random_drx_voc还有data.data_loader_one_random_multicue_uncert文件可以提供一下么，麻烦啦

**Comment by ZhouCX117** [comment]
@qinhongshuai @wenya1994 已上传在/data文件夹里，请查收~

**Comment by wenya1994** [comment]
收到，谢谢
