### ISSUE TITLE
作者是否可以提供一下白底的结果呢，需要用您的结果做一下比较

### ISSUE THREAD

**Issue by shiwanghaha** [ZhouCX117/UAED#22]

**Comment by ZhouCX117** [comment]
我在readme里面放了实验结果，是黑底的，你用cv2读取下，然后255-value，再保存下就好啦

**Comment by shiwanghaha** [comment]
> 我在readme里面放了实验结果，是黑底的，你用cv2读取下，然后255-value，再保存下就好啦

好的，谢谢了
