### ISSUE TITLE
你好，请问训练时是将PASCAL-VOC和BSDS放在一起训练的，还是分别训练的？非常感谢

### ISSUE THREAD

**Issue by wenya1994** [ZhouCX117/UAED#23]

**Comment by ZhouCX117** [comment]
你好，跟之前的实验保持一致，先用VOC pretrain，然后加载pretrain的模型后，再用BSDS数据集训练。

**Comment by wenya1994** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 下午2:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZhouCX117/UAED] 你好，请问训练时是将PASCAL-VOC和BSDS放在一起训练的，还是分别训练的？非常感谢 (Issue #23)




 
你好，跟之前的实验保持一致，先用VOC pretrain，然后加载pretrain的模型后，再用BSDS数据集训练。

**Comment by ZhouCX117** [comment]
`parser.add_argument('--resume', default=True, type=bool, help='pretrain')
parser.add_argument('--path', default="/data/private/zhoucaixia/workspace/UD_Edge/tmp/voc_pretrain_/epoch-19-checkpoint.pth", type=str)
if args.resume:
        checkpoint = torch.load(args.path)
        model.load_state_dict(checkpoint['state_dict'])
`
可以加上这几句
