### ISSUE TITLE
Model Checkpoint

### ISSUE THREAD

**Issue by rayeeli** [ZhouCX117/UAED#5]
Thank you for your wonderful work. I am interested in using your model to detect edges. Could you please provide the model checkpoints used in your paper? Thank you very much in advance!

**Comment by ZhouCX117** [comment]
The model checkpoint link is https://drive.google.com/file/d/1nv2_TZRyiQh5oU9TnGMzu313OrspD2l5/view?usp=sharing, you can have a try~

**Comment by rayeeli** [comment]
thanks so much for your reply!
