### ISSUE TITLE
would you mind sharing the detail of Multicue dataset?

### ISSUE THREAD

**Issue by Li-yachuan** [ZhouCX117/UAED#7]
Each image is flipped (horizontally, vertically, and a combination of both) at each angle?
The data is expanded by 16 times?

**Comment by ZhouCX117** [comment]
what details do you mean？

**Comment by Li-yachuan** [comment]
Each image is flipped (horizontally, vertically, and a combination of both) at each angle?
The data is expanded by 16 times?

**Comment by Li-yachuan** [comment]
> Each image is flipped (horizontally, vertically, and a combination of both) at each angle?
> The data is expanded by 16 times?

Each image is flipped (horizontally, vertically, and a combination of both) at each angle?
The data is expanded by 16 times?

**Comment by ZhouCX117** [comment]
You are right!
![image](https://github.com/ZhouCX117/UAED/assets/79554332/81617b59-5000-4947-88be-8af9874c6a6b)

**Comment by Li-yachuan** [comment]
thanks
